export const emojis = [
  '😀',
  '😃',
  '😄',
  '😁',
  '😆',
  '😅',
  '😂',
  '🤣',
  '🤗',
  '🙃',
  // '🥲',
  '🤔',
  '😊',
  '😇',
  '🙂',
  '😉',
  '😌',
  '😍',
  '🥰',
  '😘',
  '😗',
  '😙',
  '😚',
  '😋',
  '😛',
  '😝',
  '😜',
  '🤪',
  '🤨',
  '🧐',
  '🤓',
  '😎',
  '🥴',
  // '🥸',
  '🤩',
  '🥳',
  '😏',
  '😒',
  '😞',
  '😔',
  '😟',
  '😕',
  '🙁',
  '😣',
  '😖',
  '😫',
  '😩',
  '🥺',
  '😢',
  '😭',
  '😤',
  '😠',
  '😡',
  '🤬',
  '🤯',
  '😳',
  '🤤',
  '😴',
  '🤠',
  '🥵',
  '🥶',
  '😵‍💫',
  '😮‍💨',
  '😲',
  '🤧',
  '😷',
  '🤒',
  '🤕',
  '🤑',
  '🤮',
  '🤢',
  '🥴',
  '🤥',
  '🤫',
  '🤭',
  '🧐',
  '🤨',
  '🙄',
  '🤔',
  '💩',
  '🤡',
  '👻',
  '😶‍🌫️',
  '🤖',
]

export const animalsAndNature = [
  { value: '🐶', title: 'dog face' },
  { value: '🐱', title: 'cat face' },
  { value: '🐭', title: 'mouse face' },
  { value: '🐹', title: 'hamster face' },
  { value: '🐰', title: 'rabbit face' },
  { value: '🦊', title: 'fox face' },
  { value: '🦁', title: 'lion face' },
  { value: '🐯', title: 'tiger face' },
  { value: '🐨', title: 'koala' },
  { value: '🐼', title: 'panda face' },
  { value: '🐸', title: 'frog' },
  { value: '🐵', title: 'monkey face' },
]

export const foodAndDrink = [
  { value: '🍏', title: 'green apple' },
  { value: '🍎', title: 'red apple' },
  { value: '🍐', title: 'pear' },
  { value: '🍊', title: 'tangerine' },
  { value: '🍋', title: 'lemon' },
  { value: '🍌', title: 'banana' },
  { value: '🍉', title: 'watermelon' },
  { value: '🍇', title: 'grapes' },
  { value: '🍓', title: 'strawberry' },
  { value: '🍒', title: 'cherries' },
  { value: '🍍', title: 'pineapple' },
  { value: '🥥', title: 'coconut' },
]

export const activities = [
  { value: '⚽', title: 'soccer ball' },
  { value: '🏀', title: 'basketball' },
  { value: '🏈', title: 'american football' },
  { value: '⚾', title: 'baseball' },
  { value: '🎾', title: 'tennis' },
  { value: '🏐', title: 'volleyball' },
  { value: '🏓', title: 'ping pong' },
  { value: '🏸', title: 'badminton' },
  { value: '🥅', title: 'goal net' },
  { value: '⛳', title: 'golf flag in hole' },
  { value: '🎱', title: 'pool 8 ball' },
  { value: '🎳', title: 'bowling' },
]

export const travelAndPlaces = [
  { value: '✈️', title: 'airplane' },
  { value: '🚗', title: 'car' },
  { value: '🚕', title: 'taxi' },
  { value: '🚙', title: 'SUV' },
  { value: '🚌', title: 'bus' },
  { value: '🚎', title: 'trolleybus' },
  { value: '🚝', title: 'monorail' },
  { value: '🚂', title: 'steam locomotive' },
  { value: '🚀', title: 'rocket' },
  { value: '🚁', title: 'helicopter' },
  { value: '🛳️', title: 'passenger ship' },
  { value: '⛵', title: 'sailboat' },
]

export const objects = [
  { value: '💻', title: 'laptop' },
  { value: '📱', title: 'mobile phone' },
  { value: '🔧', title: 'wrench' },
  { value: '🔨', title: 'hammer' },
  { value: '💡', title: 'light bulb' },
  { value: '🎁', title: 'gift' },
  { value: '📦', title: 'package' },
  { value: '🔒', title: 'lock' },
  { value: '📚', title: 'books' },
  { value: '🖊️', title: 'pen' },
  { value: '🕰️', title: 'mantelpiece clock' },
  { value: '🎮', title: 'video game controller' },
]

export const symbols = [
  { value: '❤️', title: 'red heart' },
  { value: '⭐', title: 'star' },
  { value: '✔️', title: 'check mark' },
  { value: '❌', title: 'cross mark' },
  { value: '⚠️', title: 'warning' },
  { value: '❓', title: 'question mark' },
  { value: '❗', title: 'exclamation mark' },
  { value: '💲', title: 'heavy dollar sign' },
  { value: '⚡', title: 'high voltage' },
  { value: '💔', title: 'broken heart' },
  { value: '♻️', title: 'recycling symbol' },
  { value: '🔄', title: 'counterclockwise arrows button' },
]
